### PR TITLE
docs(airflow): Airflow DAG request issue template

### PR DESCRIPTION
**Pull request by luabida**
Issue template for requesting a new DAG to EpiGraphHub.

### CODE REVIEW

**Comment by luabida** [comment]
fix #36

**Comment by luabida** [comment]
fix #120

**Comment by luabida** [comment]
fix #137

**Comment by luabida** [comment]
fix #141

**Comment by luabida** [comment]
Cron tests failed, fixed on #133

**Comment by xmnlab** [comment]
@luabida could you rebase your PR pls?

**Review by xmnlab — APPROVED** [review]
LGTM! as this PR doesn't impact CI at all. I will merge that
thanks @luabida

**Pull request merged**
