### PR TITLE
chore(docker): Add docker for celery redis and flower

### PR DESCRIPTION
**Pull request by xmnlab**
This PR aims to create a docker services for celery redis and flower

### CODE REVIEW

**Review by fccoelho — APPROVED** [review]

**Review by fccoelho — APPROVED** [review]

**Comment by xmnlab** [comment]
there is a small error that I need to fix before merging

**Review by fccoelho — APPROVED** [review]

**Comment by xmnlab** [comment]
added service for celery beat.

it is raising a new error for async queries: `KeyError: 'query_id'`.
I am investigating the problem.

**Comment by fccoelho** [comment]
Have you tried disabling the Redis server on the host? Maybe it is getting the query instead of the instance in the container. just an idea...

**Comment by xmnlab** [comment]
thanks @fccoelho I will take a look. I will give more updates soon.

**Comment by xmnlab** [comment]
@fccoelho I managed to fix the problem locally.
I am now trying to run it on the staging server
Hope to have it ready today and I will refactor the configuration file.

**Comment by fccoelho** [comment]
I have tested on the staging server and it seems to be working normally

**Pull request merged**
