### PR TITLE
chore(refactor): Refactor of Data Collection modules to match ETL workflow

### PR DESCRIPTION
**Pull request by luabida**
Refactor:

- [x] foph
- [x] owid
- [x] colombia

depends on https://github.com/thegraphnetwork/epigraphhub_py/pull/193

### CODE REVIEW

**Review by fccoelho — COMMENTED** [review]
The naming is much better now! Good job @luabida !

**Comment by luabida** [comment]
I've noticed the DAGs run step passed, but it actually shouldn't. Have to fix it

**Comment by luabida** [comment]
@xmnlab do you have any idea on why CI reproduces different output than when executed in a shell? It should at least show the logs, I think

https://github.com/thegraphnetwork/EpiGraphHub/pull/151/checks#step:9:53

**Comment by xmnlab** [comment]
@luabida do you mind rebasing your code on top of the main branch pls? thanks!

**Review by fccoelho — APPROVED** [review]

**Pull request merged**
